config/routes.rb
Rails.application.routes.draw do
  
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :show, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings, only: [:show]
  end
    resources :listings do
      resource :verify, only: %w(update destroy)
      # member do
      #   put 'verify'
      # end
      resources :bookings
    end

#nested routes suck
  post 'braintree/checkout'
  get "/users/:id/bookings" => "bookings#index", as: "show_all_booking"
  get "/users/:id/bookings/:booking_id" => "bookings#user_show", as: "show_user_booking"
  get "/users/:user_id/listings" => "listings#user_listing", as: "show_user_listing"
  get "/listings" => "listings#all", as: "all_listing"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root 'home#index'
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
  	@listing = Listing.find(params[:listing_id])
  	@check_in = params[:check_in]
  	@check_out = params[:check_out]
  	@client_token = Braintree::ClientToken.generate
  end

  def checkout
  	booking = Booking.new
  	booking.check_in = params[:check_in].to_date
  	booking.check_out = params[:check_out].to_date
  	booking.user_id = current_user.id
  	booking.listing_id = params[:listing_id]
  	nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  	result = Braintree::Transaction.sale(
  		:amount => "#{booking.total_cost}",
  		:payment_method_nonce => nonce_from_the_client,
  		:options => {
  			:submit_for_settlement => true
  			})

  	if result.success?
  		booking.save
      BookingJob.perform_now(booking)
  		redirect_to :root , :flash => {:success => "Transaction successful!"}
  	else
  		redirect_to braintree_new_path, :flash => {:error => "Transaction failed.Please try again."}
  	end
  end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/views/braintree/new.html.erb
<div class='container'>
  <div class="form-group jumbotron my-4">

      <%= form_for :checkout_form, url: braintree_checkout_path(check_in: @check_in, check_out: @check_out, listing_id: @listing), html: { id: "cardForm"} do |form| %>

        <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
        <div id="card-number" class="hosted-field form-control"></div>

        <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
        <div id="expiration-date" class="hosted-field form-control"></div>

        <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
        <div id="cvv" class="hosted-field form-control"></div>

        <%= form.hidden_field "payment_method_nonce" %>

        <div class="button-container">
          <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
        </div>
      <% end %>
    </div>
</div>
    <!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>