config/routes.rb
Rails.application.routes.draw do
  
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :show, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings, only: [:show]
  end
    resources :listings do
      resource :verify, only: %w(update destroy)
      # member do
      #   put 'verify'
      # end
      resources :bookings
    end

#nested routes suck
  post 'braintree/checkout'
  get "/users/:id/bookings" => "bookings#index", as: "show_all_booking"
  get "/users/:id/bookings/:booking_id" => "bookings#user_show", as: "show_user_booking"
  get "/users/:user_id/listings" => "listings#user_listing", as: "show_user_listing"
  get "/listings" => "listings#all", as: "all_listing"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root 'home#index'
end

app/models/listing.rb
class Listing < ApplicationRecord
	
	include Filterable
	attr_accessor :images
	has_many :bookings
	belongs_to :user
	acts_as_taggable
	acts_as_taggable_on :interests, :rules, :locations
	self.per_page = 10
	mount_uploaders :images, ImagesUploader
	scope :city, -> (city) {where("city = ?", "#{city}")}
	scope :min_stay, -> (stay) {where("min_stay >= ?", "#{stay}")}
	scope :number_of_rooms, -> (rooms) {where("number_of_rooms >= ?", "#{rooms}")}
	scope :rent, -> (rent) {where("rent < ?", "#{rent}")}

	

	def self.search(search)
		where("listing_name ILIKE ? OR country ILIKE ? OR city ILIKE?", "%#{search}%", "%#{search}%", "%#{search}%")
	end

	def verified?
		verified_at != nil
	end

	def verify
		self.verified_at = Time.now
	end

	def verify!
		verify
		save!
	end

	def unverify
		self.verified_at = nil
	end

	def unverify!
		unverify
		save!
	end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def new
		allowed?(action: @listing= Listing.new, user:current_user)
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def edit
		allowed?(action: @listing = Listing.find(params[:id]), user:current_user)
	end

	def user_listing
		@user = User.find(params[:user_id])
		@listings = @user.listings
	end

	def create
		@listing = current_user.listings.new(listing_params)
		if @listing.save
			redirect_to @listing
		else
			redirect_to template: "listings/new"
		end
	end

	def update
		@listing = current_user.listings.update(listing_params)
		if @listing != nil 
			if @listing.save
				redirect_to @listing
			else
				redirect_to template: "listings/edit"
			end
		else
			redirect_to '/'
			flash[:notice] = "You haven't made a listing yet"
		end
	end

	def index
		@listings = Listing.all
		if params[:search]
			
			# @listings = Listing.search(params[:search]).page(params[:page]).order("created_at DESC")
			@listings = Listing.filter(params.slice(:city, :min_stay, :number_of_rooms, :rent)).page(params[:page]).order("created_at DESC")
		else
			@listings = Listing.all.page(params[:page]).order('created_at DESC')
		end

	end

	def verify
		@listing = Listing.find(params[:id])
		@listing.update_attributes(:verification => true)
		flash[:notice] = "Listing verified"
	end


	private

	def listing_params
		params.require(:listing).permit(:description, :status, :city, :country, :address, :number_of_rooms, :rent, :min_stay, :private_room, :shared_room, :entire_house, :listing_name, :place_type, :state, :zipcode,  :tag_list, {images:[]})
	end
end

app/helpers/listings_helper.rb
module ListingsHelper

	def link_to_toggle_listing_verify(listing)
		url = listing_verify_path(listing)
		
		if listing.verified?
			link_to_with_icon('glyphicon glyphicon-ok', 'Verify', url, {
				method: 'DELETE',
				remote: true,
				class: 'btn btn-primary',
				})
		else
			link_to_with_icon('glyphicon glyphicon-remove', 'Unverify', url, {
				method: 'PUT',
				remote: true,
				class: 'btn btn-primary',
				})
		end
	end

	def link_to_with_icon(icon_css, title, url, options = {})
		icon = content_tag(:i, nil, class: icon_css)
		title_with_icon = icon << ' '.html_safe << h(title)
		link_to(title_with_icon, url, options)
	end

end

app/views/listings/_form.slim
.text-field
  = form.label :listing_name
  = form.text_field :listing_name
.text-field
  = form.label :status
  = form.text_field :status
.text-field
  = form.label :country
  = form.text_field :country
.text-field
  = form.label :state
  = form.text_field :state
.text-field
  = form.label :zipcode
  = form.text_field :zipcode
.text-field
  = form.label :city
  = form.text_field :city
.text-field
  = form.label :address
  = form.text_field :address
.text-field
	= form.label :rent
	= form.text_field :rent
.number-field
	= form.label :min_stay
	= form.number_field :min_stay, min: 1
.number-field
  = form.label :number_of_rooms
  = form.number_field :number_of_rooms, min: 1
.text-field
  = form.label :description
  = form.text_field :description
.form-group
  label for="place_type"  Place Type:
  select#place_type.form-control
    option Private Room
    option Shared Room
    option Entire House
.text-field
	=form.label :tag_list
	=form.text_field :tag_list, parse: true
.file-field
  =form.file_field :images, multiple: true

app/views/listings/all.slim
h1 
 All listings

	table =@listing.each do |list|
     tr
    th Description
    th Status
    th City
    th Country
    th Address
    th Rent
    th Number of Rooms
    th Minimum Stay
    th Private room?
    th Shared room?
    th Entire house?
     tr
    th= @list.description
    th= @list.status
    th= @list.city
    th= @list.country
    th= @list.address
    th= @list.rent
    th= @list.number_of_rooms
    th= @list.minimum_stay
    th= @list.private_room
    th= @list.shared_room
    th= @list.entire_house

app/views/listings/edit.slim
#listing.create-listing
  h2 Edit Listing

  = form_for @listing, :html => {:multipart => true} do |form|
    = render partial: '/listings/form', object: form
    .submit-field

      = form.submit
    .other-links
      = link_to t(".sign_in"), sign_in_path

app/views/listings/index.html.erb
 <div class= "panel panel-default">
 	<div class= "panel-body">
 		<% if @listings.blank? %>
      		<h4>There are no listings containing the term <%= params[:search] %>.</h4>
 		<% end %>
	</div>
</div>

<div class="row">
	<% if signed_in?%>
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listing", listing_path(current_user), class:"sidebar-link active"%></li>
			<li class="sidebar-item"><%= link_to "Your Reservations", listing_path(current_user), class:"sidebar-link"%></li>
		</ul>
	</div>
	<% end %>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">
				<% if @listings.empty? == false %>
					
					<%= will_paginate @listings %>
					
					<% @listings.each do |list| %>
						<div class="row">
							<div class="col-md-2">
								<% if list.images[0] != nil %>
								<%= link_to (image_tag list.images[0].url(:thumb), class: 'image-thumb'), listing_path(list) %>
								<% end %>
							</div>
							<div class="col-md-7">
								
							</div>
							<div class="col-md-3 right">
								<h4><%= link_to ( list.listing_name), listing_path(list) %></h4>
								<%= link_to "Update", edit_listing_path(list), class: "btn btn-primary"%>
								<% if signed_in? %>
								<% if current_user.superadmin? %>
								
								<div>
									<%= link_to_toggle_listing_verify list %>
								</div>
								<% end %>
								<% end %>
							</div>
						</div>
						<hr/>
					<% end %>
				<% else %>
					<p> No listings have been posted.</p>
				<% end %>
			</div>
		</div>
	</div>	
</div>

app/views/listings/new.slim
#listing.create-listing
  h2 Create Listing

  = form_for @listing, :html => {:multipart => true} do |form|
    = render partial: '/listings/form', object: form
    .submit-field

      = form.submit
    .other-links
      = link_to t(".sign_in"), sign_in_path

    

app/views/listings/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class= "col-md-8 col-md-offset-2">
				<%= image_tag @listing.images[0].url, class: "img-responsive" if @listing.images[0] != nil %>
			</div>
		</div>
		<!-- Main Info -->
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-3 text-center">
						<% if @listing.user.avatar.url %>
						<%= image_tag @listing.user.avatar.url, class: "img-circle avatar-large" %>
						<% end %>
						<br/><br/>
						
						<%= @listing.user.first_name %> <%= @listing.user.last_name %>
					</div>
					<div class="col-md-9">
						<h4><%= @listing.listing_name %></h4>
						<%= @listing.address %>

						<div class="row text-centre row-space-1">
							<div class="col-sm-3">
								<i class="fa fa-home fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-user fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-bed fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-ship fa-2x"></i>
							</div>
						</div>
						<div class="row text-centre row-space-1">
							<div class="col-sm-3">
								<%= @listing.number_of_rooms %> 
								<% if @listing.number_of_rooms != nil%>
								<%= @listing.number_of_rooms > 1 ? "Guests":"Guest"  %>
								<% end %>
							</div>
							<div class="col-sm-3">
								<%= @listing.min_stay %>
								<% if @listing.min_stay != nil %>
								 <%= @listing.min_stay > 1 ? "Days":"Days"  %>
								 <% end %>
							</div>
							
						</div>

					</div>
				</div>
			</div>
			<div class="col-md-4">
				<!-- Reservation form <-->
				<%= render 'bookings/form' %>
				

			</div>

		</div>
		
		
		<!-- About -->
		<div class="row">
			<div class="col-md-12">
				<h2>About This Listing</h2>
				<p><%= @listing.description%></p>
			</div>
		</div>

		<!-- Amenities -->
		<div class="row">
			<div class="col-md-2">
				<h2>Room Type</h2>
			</div>
			<div class="row">
				<div class="col-md-10">
					<div class="row">
						<div class="col-md-6">
							<ul class="room-type">
								<li class="<%= 'text-line-through' unless @listing.private_room%>">Private Room</li>
								<li class="<%= 'text-line-through' unless @listing.shared_room%>">Shared Room</li>
								<li class="<%= 'text-line-through' unless @listing.entire_house%>">Entire House</li>	
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">
					<% if @listing.images %>
						<ol class="carousel-indicators">
							<% for i in 0..(@listing.images.count - 1) %>
								<li data-target="#myCarousel" data-slide-to= "i" class="<%= 'active' if i == 0 %>"</li>
							<% end %>
						</ol>
					<% end %>
						<div class="carousel-inner" role="listbox">
							<% if @listing.images %>
								<% for i in 0..(@listing.images.count - 1) %>
									<div class="item <%= 'active' if i == 0%>">
										<%= image_tag @listing.images[i].url %>
									</div>
								<% end %>
							<% end %>
						</div>

						<a class="left carousel-control" href="#myCarousel" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left"></span>
							<span class="sr-only">Previous</span>
						</a>
						<a class="right carousel-control" href="#myCarousel" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right"></span>
							<span class="sr-only">Next</span>
						</a>	

				</div>		
			</div>
		</div>
		<br/>
		<hr>
	</div>
</div>

app/views/listings/user_listing.html.erb
<p>hello</p>