config/routes.rb
Rails.application.routes.draw do
  
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :show, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings, only: [:show]
  end
    resources :listings do
      resource :verify, only: %w(update destroy)
      # member do
      #   put 'verify'
      # end
      resources :bookings
    end

#nested routes suck
  post 'braintree/checkout'
  get "/users/:id/bookings" => "bookings#index", as: "show_all_booking"
  get "/users/:id/bookings/:booking_id" => "bookings#user_show", as: "show_user_booking"
  get "/users/:user_id/listings" => "listings#user_listing", as: "show_user_listing"
  get "/listings" => "listings#all", as: "all_listing"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root 'home#index'
end

app/views/shared/_facebook_login.html.erb
<% facebook_logo = "fb-art.png"  %>

  <%= link_to image_tag(facebook_logo, size: '20') + " Login with Facebook", "/auth/facebook", class: "btn btn-primary facebook-btn btn-block" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Airbnb", root_path, class: "navbar-brand" %>
		</div>
		<div id="flash">  
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    
    
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">

				<% if(!signed_in?)%>
					<li><%= link_to "Sign In", sign_in_path %></li>
					<li><%= link_to "Sign Up", sign_up_path %></li>
				<% else %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="buttpn" aria-haspopup="true" aria-expanded="false">
						<% if current_user.avatar.url != nil %>
							<%= image_tag current_user.avatar.url, class: "img-circle avatar-small" %>&nbsp;
						<% end %>
						<%= current_user.first_name %> <%=current_user.last_name%><span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Your Bookings", show_all_booking_path(current_user)%> </li>	
							<li><a href="#">Wish Lists</a></li>	
							<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
							<li role="seperator" class="divider"></li>
							<li><%= link_to "My Profile", user_path(current_user) %></li>
							<li><%= link_to "Log Out", sign_out_path, method: :delete%></li>
						</ul>
					</li>
				
				<li>
					<a href="#"><i class="fa fa-envelope-o"></i> Messages</a>
				</li>
				<li>
					<%= link_to 'Become a host', new_listing_path %>
				</li>	
				<% end %>
			</ul>
		</div>
	</div>
</nav>