config/routes.rb
Rails.application.routes.draw do
  
  get 'braintree/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users", only: [:create, :edit, :show, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings, only: [:show]
  end
    resources :listings do
      resource :verify, only: %w(update destroy)
      # member do
      #   put 'verify'
      # end
      resources :bookings
    end

#nested routes suck
  post 'braintree/checkout'
  get "/users/:id/bookings" => "bookings#index", as: "show_all_booking"
  get "/users/:id/bookings/:booking_id" => "bookings#user_show", as: "show_user_booking"
  get "/users/:user_id/listings" => "listings#user_listing", as: "show_user_listing"
  get "/listings" => "listings#all", as: "all_listing"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@user = current_user
		@listing = Listing.all
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <!-- Page Content -->
    <div class="container">
    
      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3">Airbnb</h1>
        <p class="lead">Search for accomodation for your next trip!</p>
        <%= form_tag(listings_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search..", :required => 'required' %>
        
            <%= text_field_tag :city, params[:filter], placeholder: "city" %>
            <%= number_field_tag :min_stay, params[:filter], placeholder: "1" %>
            <%= number_field_tag :number_of_rooms, params[:filter], placeholder: "1" %> <br>
            <%= range_field_tag :rent, nil, {min: 100, max: 1000, :step => 10, value: params[:filter], id:"myRange" }%>
            <p> Price: <span id="myValue"></span></p> 
            <%= submit_tag "Search", :name => nil %>
        <% end %>
        <a href="#" class="btn btn-primary btn-lg">Find your dream destination</a>
      </header>

      <!-- Page Features -->
      <div class="row text-center">
      <% for i in 1..4 %>
        <% if Listing.all[i] != nil %>
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
          	
            <img class="card-img-top" src="http://via.placeholder.com/250x150" alt="">
            <div class="card-body">
              <h4 class="card-title"><%= Listing.find(i).listing_name%></h4>
              <p class="card-text"></p>
            </div>
            <div class="card-footer">
              <%= link_to 'Find Out More!', listing_path(i), class:"btn btn-primary" %>
            </div>
          </div>
        </div>

		<% end%>
    <%end %>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

   

  </body>

</html>